export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const RETRIEVE_EMPLOYEES = "RETRIEVE_EMPLOYEES";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_ALL_EMPLOYEES = "DELETE_ALL_EMPLOYEES";

export const ADD_RESULT = "ADD_RESULT";

export const CREATE_QUIZ = "CREATE_QUIZ";
export const RETRIEVE_QUIZ = "RETRIEVE_QUIZ";
export const UPDATE_QUIZ = "UPDATE_QUIZ";
export const DELETE_QUIZ = "DELETE_QUIZ";